# Set this to the level of the speed effect you'd like to be applied when a player steps on a dirt_path. Default is 2.
SpeedEffectLevel: 2

# The amount of time (in seconds) that the speed effect will be applied after stepping on a dirt path. Default is 2.
SpeedEffectDuration: 2

# The message that will be displayed in a player's hot bar while walking on a dirt path block
actionBarMessage: "Faster than Light Mode"